# 常见异常
ava.lang.Throwable
* java.lang.Error:一般不编写针对性的代码进行处理
* java.lang.Exception:可以进行异常处理
   * 	编译时异常(checked)
           * 	IOEXception
                * 	FileNotFoundException
               * 	ClassNotFoundException
       
       * 	运行时异常(unchecked)
             * 	NullPointerException
             * 	ArrayIndexOutOfBoundsException
             * 	ClassCaseException
             * 	NumberFormatException
             * 	InputMismatchException
             * 	ArithmaticException
# 异常处理机制一：try-catch-finally
## try
捕获异常的第一步是用try{…}语句块选定捕获异常的范围，将可能出现异常的代码放在try语句块中。
## catch(Exceptiontypee)
在catch语句块中是对异常对象进行处理的代码。每个try语句块可以伴随**一个或多个**catch语句，用于处理可能产生的不同类型的异常对象。
* 捕获异常的有关信息：与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。
  * getMessage() 获取异常信息，返回字符串
  * printStackTrace() 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。
## finally
&nbsp;&nbsp;&nbsp;&nbsp;捕获异常的最后一步是通过finally语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理。
&nbsp;&nbsp;&nbsp;&nbsp;不论在try代码块中是否发生了异常事件，catch语句是否执行，catch语句是否有异常，catch语句中是否有return，finally块中的语句都会被执行。  
&nbsp;&nbsp;&nbsp;&nbsp;finally语句和catch语句是任选的。
## 异常的处理:抓抛模型

 * 过程一:“抛”：程序在征程执行过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象并将此对象抛出。一旦抛出对象以后，其后的代码就不再执行。
 * 过程二:“抓”:可以理解为异常的处理方式：① try-catch-finally  ② throws
## try-catch-finally的使用
```java
try{
		//可能出现异常的代码
 }catch(异常类型1 变量名1){
 		//处理异常的方式1
 }catch(异常类型2 变量名2){
 		//处理异常的方式2
 }catch(异常类型3 变量名3){
 		//处理异常的方式3
 }
 ...
 finally{
		//一定会执行的代码
 }
```
 **说明:**
1. finally是可选的。
2. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配。
3. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码。
4. catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓。catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则，报错
5. 常用的异常对象处理的方式： ① String  getMessage()       ② printStackTrace()
 1. 在try结构中声明的变量，在出了try结构以后，就不能再被调用
 7. try-catch-finally结构可以嵌套  

**体会：**
 * 体会1：使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
 * 体会2：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。
# 异常处理机制二：throws
throws + 异常类型

1. "throws + 异常类型"写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。
一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
关于异常对象的产生:① 系统自动生成的异常对象② 手动生成一个异常对象，并抛出(throw) 
2. 体会：**try-catch-finally:真正的将异常给处理掉了。
 throws的方式只是将异常抛给了方法的调用者。并没有真正将异常处理掉。**
# 子类关于异常的注意点
1. **子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型**
2. 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果 子类重写的方法中有异常，必须使用try-catch-finally方式处理。
3. 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。
 */
# 手动抛出异常
首先要生成异常类对象，然后通过throw语句实现抛出操作(提交给Java运行环境)
可以抛出的异常必须是Throwable或其子类的实例。
如：
```java
 void test() throws Exception {
        if (n > 0) {
            System.out.println("没问题");
        } else
            throw new Exception("您输入的数据非法！");
    }
```
# 用户自定义异常类
一般地，用户自定义异常类都是RuntimeException的子类。
自定义异常类通常需要编写几个重载的构造器。
自定义异常需要提供serialVersionUID
自定义的异常通过throw抛出。
自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。